#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 RenoSeven

"""Gzip-compress web UI files and emit C++ PROGMEM embed sources.

Scans assets/ for index.html, script.js, style.css, and related files;
optionally minifies supported types, gzip-compresses at level 9, and writes
include/web/assets.h plus src/web/assets.cpp.

CLI: embed_assets.py [-f] [-q] [--no-strip] [--no-mangle]

Library:
    from embed_assets import embed_assets
    embed_assets()              # skip when outputs are up to date
    embed_assets(force=True)    # always regenerate; returns 0 on success
"""

from __future__ import annotations

import argparse
import gzip
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# --- Paths ---

SCRIPT_PATH = Path(__file__).resolve()
SCRIPT_NAME = SCRIPT_PATH.name
SCRIPTS_DIR = SCRIPT_PATH.parent
REPO_DIR = SCRIPTS_DIR.parent
MINIFY_PATH = SCRIPTS_DIR / "minify.mjs"
PACKAGE_JSON = SCRIPTS_DIR / "package.json"
EMBED_DEPS = (SCRIPT_PATH, MINIFY_PATH, PACKAGE_JSON)


# --- Constants ---

ASSETS_DIR = "assets"
OUT_HEADER = "include/web/assets.h"
OUT_SOURCE = "src/web/assets.cpp"
BYTES_PER_LINE = 16

HEADER_TEMPLATE = """\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 RenoSeven
//
// Declares gzip-compressed web UI assets in PROGMEM.
//
// Sized arrays let callers use sizeof(Assets::INDEX_HTML). Generated by scripts/embed_assets.py.
//
// Auto-generated by scripts/embed_assets.py - do not edit.

#pragma once

#include <cstddef>
#include <cstdint>
#include <pgmspace.h>

"""

SOURCE_TEMPLATE = """\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 RenoSeven
//
// PROGMEM byte arrays for gzip-compressed web UI assets.
//
// Flow: scripts/embed_assets.py minifies assets/, gzip-compresses, emits this file.
//
// Auto-generated by scripts/embed_assets.py - do not edit.

#include "web/assets.h"

"""

# --- Discovery ---


def asset_dir(base: Path) -> Path:
    return base / ASSETS_DIR


def find_assets(base: Path) -> list[Path]:
    d = asset_dir(base)
    if not d.is_dir():
        return []
    return sorted(p for p in d.rglob("*") if p.is_file())


def symbol_name(base: Path, path: Path) -> str:
    rel = path.relative_to(asset_dir(base))
    parts = re.split(r"[./\-]", str(rel))
    return "_".join(parts).upper()


# --- Staleness ---


def _output_mtime(*out_paths: Path) -> float | None:
    if not all(p.is_file() for p in out_paths):
        return None
    return min(p.stat().st_mtime for p in out_paths)


def _embed_tooling_stale(output_ts: float) -> bool:
    return any(
        path.is_file() and path.stat().st_mtime > output_ts for path in EMBED_DEPS
    )


def is_stale(base: Path, *out_paths: Path) -> bool:
    ts = _output_mtime(*out_paths)
    if ts is None:
        return True
    if _embed_tooling_stale(ts):
        return True
    return any(p.stat().st_mtime > ts for p in find_assets(base))


def is_asset_stale(
    asset: Path,
    output_ts: float | None,
    *,
    force: bool,
    tooling_stale: bool,
) -> bool:
    if force or tooling_stale:
        return True
    if output_ts is None:
        return True
    return asset.stat().st_mtime > output_ts


# --- Minify ---

MINIFY_SUFFIXES = frozenset({".js", ".css", ".html"})


def _ensure_npm_deps(npm_root: Path) -> None:
    if (npm_root / "node_modules" / "esbuild" / "package.json").is_file():
        return
    raise RuntimeError(f"npm dependencies missing; run: npm install (in {npm_root})")


def _node_minify(path: Path, *, mangle: bool = True) -> str:
    _ensure_npm_deps(SCRIPTS_DIR)
    cmd = ["node", str(MINIFY_PATH), str(path.resolve())]
    if path.suffix.lower() == ".js" and not mangle:
        cmd.append("--no-mangle")
    result = subprocess.run(
        cmd,
        capture_output=True,
        cwd=SCRIPTS_DIR,
        check=False,
    )
    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(detail or f"minify {path.name} failed")
    if result.stderr:
        sys.stderr.write(result.stderr.decode("utf-8", errors="replace"))
    return result.stdout.decode("utf-8")


# --- Prepare ---


def prepare_asset_bytes(
    path: Path, *, strip: bool = True, mangle: bool = True
) -> tuple[bytes, int]:
    raw = path.read_bytes()
    payload = raw

    if strip and path.suffix.lower() in MINIFY_SUFFIXES:
        payload = _node_minify(path, mangle=mangle).encode("utf-8")

    compressed = gzip.compress(payload, compresslevel=9, mtime=0)
    return compressed, len(compressed)


# --- File I/O ---


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, delete=False
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    tmp_path.replace(path)


# --- Rendering ---


def format_byte_array(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        lines.append("        " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def render_header(
    base: Path, assets: list[Path], *, strip: bool = True, mangle: bool = True
) -> str:
    parts = [HEADER_TEMPLATE, "namespace Assets {\n\n"]
    for path in assets:
        sym = symbol_name(base, path)
        rel = path.relative_to(base)
        _, size = prepare_asset_bytes(path, strip=strip, mangle=mangle)
        parts.append(f"    // --- {rel} ---\n\n")
        parts.append(f"    extern const uint8_t {sym}[{size}] PROGMEM;\n\n")
    parts.append("} // namespace Assets\n")
    return "".join(parts)


def render_source(
    base: Path, assets: list[Path], *, strip: bool = True, mangle: bool = True
) -> str:
    parts = [SOURCE_TEMPLATE, "namespace Assets {\n\n"]
    for path in assets:
        sym = symbol_name(base, path)
        rel = path.relative_to(base)
        compressed, size = prepare_asset_bytes(path, strip=strip, mangle=mangle)

        parts.append(f"    // --- {rel} ---\n\n")
        parts.append(f"    const uint8_t {sym}[{size}] PROGMEM = {{\n")
        parts.append(format_byte_array(compressed))
        parts.append("\n    };\n\n")

    parts.append("} // namespace Assets\n")
    return "".join(parts)


# ============================================================
# Public API
# ============================================================


def embed_assets(
    base: Path | None = None,
    *,
    force: bool = False,
    strip: bool = True,
    mangle: bool = True,
    quiet: bool = False,
) -> int:
    """Regenerate include/web/assets.h and src/web/assets.cpp when stale or forced."""
    root = REPO_DIR if base is None else base.resolve()
    h_path = root / OUT_HEADER
    cpp_path = root / OUT_SOURCE

    assets = find_assets(root)
    if not assets:
        print(f"Error: No files found in {asset_dir(root)}", file=sys.stderr)
        return 1

    if not force and not is_stale(root, h_path, cpp_path):
        if not quiet:
            for p in assets:
                print(f"{p.relative_to(root)}: up to date.", flush=True)
        return 0

    output_ts = _output_mtime(h_path, cpp_path)
    tooling_stale = output_ts is None or _embed_tooling_stale(output_ts)

    write_atomic(h_path, render_header(root, assets, strip=strip, mangle=mangle))
    write_atomic(cpp_path, render_source(root, assets, strip=strip, mangle=mangle))

    if not quiet:
        strip_suffix = "" if strip else " (no strip)"
        for p in assets:
            rel = p.relative_to(root)
            if is_asset_stale(p, output_ts, force=force, tooling_stale=tooling_stale):
                print(f"{rel}: embedded{strip_suffix}.", flush=True)
            else:
                print(f"{rel}: up to date.", flush=True)
    return 0


# ============================================================
# CLI
# ============================================================


def create_parser() -> argparse.ArgumentParser:
    cmd = f"./{SCRIPT_NAME}"
    parser = argparse.ArgumentParser(
        description=(
            "Embed gzip-compressed assets into "
            "include/web/assets.h and src/web/assets.cpp."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            f"examples:\n"
            f"  {cmd}               # regenerate when inputs are newer\n"
            f"  {cmd} --force       # always regenerate\n"
            f"  {cmd} --no-strip    # gzip source files as-is (no minify)\n"
            f"  {cmd} --no-mangle   # minify JS without renaming identifiers"
        ),
    )
    parser.add_argument(
        "-f",
        "--force",
        action="store_true",
        help="always regenerate, even when up to date",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="suppress output when assets are up to date",
    )
    parser.add_argument(
        "--no-strip",
        action="store_true",
        help="skip minification; gzip assets/ source files as-is",
    )
    parser.add_argument(
        "--no-mangle",
        action="store_true",
        help="minify JS but keep function/variable names (minifyIdentifiers=false)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = create_parser().parse_args(argv)
    return embed_assets(
        force=args.force,
        strip=not args.no_strip,
        mangle=not args.no_mangle,
        quiet=args.quiet,
    )


if __name__ == "__main__":
    raise SystemExit(main())
